replicaCount: 1

image:
  repository: "ashfaqr27/myapp:latest"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080

#mysql:
#  host : 35.222.143.126
#  username: user
#  password: password
#  database: mydb
