replicaCount: 1

image:
  repository: "ashfaqr27/myapp:latest"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080

mysql:
  image: mysql:8.0
  username: user
  password: password
  database: mydb
