replicaCount: 1

image:
  repository: "us-central1-docker.pkg.dev/festive-shield-433206-t8/my-docker-repo-2/myapp"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080

mysql:
  image: mysql:8.0
  username: user
  password: password
  database: mydb
