name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: my-gcp-project
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure kubectl
      run: gcloud container clusters get-credentials my-gke-cluster --region us-central1 --project my-gcp-project

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/my-gcp-project/myapp:latest .
        docker push gcr.io/my-gcp-project/myapp:latest

    - name: Deploy with Helm
      run: |
        helm upgrade --install myapp ./helm/myapp --set image.repository=gcr.io/my-gcp-project/myapp --set image.tag=latest
