name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Create Kubernetes cluster (if necessary)
        run: |
            gcloud container clusters create my-gke-cluster --region us-central1 --num-nodes=1 --disk-size=30 || true

      - name: Configure kubectl
        run: gcloud container clusters get-credentials my-gke-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp:latest

      - name: Deploy with Helm
        run: |
          helm upgrade --install myapp ./helm/myapp --set image.repository=gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp --set image.tag=latest
